services:
    LOM\APIBundle\Controller\ListController:
        class:     "LOM\APIBundle\Controller\\ListController"
        arguments: ["@doctrine.orm.entity_manager"]
    
    LOM\APIBundle\Controller\ListItemController:
        class:     "LOM\APIBundle\Controller\\ListItemController"
        arguments: ["@doctrine.orm.entity_manager"]

    LOMAPIBundle.api_doc.extractor.api:
        class: LOM\APIBundle\Parser\Api
        tags:
        - { name: nelmio_api_doc.extractor.parser }
        arguments: ["@nelmio_api_doc.parser.jms_metadata_parser", "@nelmio_api_doc.parser.validation_parser"]
